[build]
  # Build command
  command = "chmod +x build.sh && ./build.sh"
  
  # Directory to publish (relative to root of your repo)
  publish = "frontend/dist"
  
  # Node.js version
  node_bundler = "esbuild"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # NPM config
  NPM_CONFIG_PRODUCTION = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (you can set these in Netlify dashboard instead)
# [build.environment]
#   VITE_API_BASE_URL = "https://your-backend-url.com/api"